// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2FLkeS3SNU4NokYGCM2iW1u1Z5wXGYX0',
    appId: '1:170319084683:web:26733ff3ef97cff7aaa88e',
    messagingSenderId: '170319084683',
    projectId: 'jaiza-namaz',
    authDomain: 'jaiza-namaz.firebaseapp.com',
    storageBucket: 'jaiza-namaz.firebasestorage.app',
    measurementId: 'G-NKRW2RJB43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Hj5hMUoR4B2olPxevrHDNxSqni3jLKY',
    appId: '1:170319084683:android:51da85dfdaf33b76aaa88e',
    messagingSenderId: '170319084683',
    projectId: 'jaiza-namaz',
    storageBucket: 'jaiza-namaz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4qP1Hm6JnREAMTEW5eqDpl6lBtZP4K4E',
    appId: '1:170319084683:ios:35080d2a2c5d5b5eaaa88e',
    messagingSenderId: '170319084683',
    projectId: 'jaiza-namaz',
    storageBucket: 'jaiza-namaz.firebasestorage.app',
    iosBundleId: 'com.alislaacademy.jayzanamaz.jaizaNamaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4qP1Hm6JnREAMTEW5eqDpl6lBtZP4K4E',
    appId: '1:170319084683:ios:35080d2a2c5d5b5eaaa88e',
    messagingSenderId: '170319084683',
    projectId: 'jaiza-namaz',
    storageBucket: 'jaiza-namaz.firebasestorage.app',
    iosBundleId: 'com.alislaacademy.jayzanamaz.jaizaNamaz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2FLkeS3SNU4NokYGCM2iW1u1Z5wXGYX0',
    appId: '1:170319084683:web:e134b559c5bdb8acaaa88e',
    messagingSenderId: '170319084683',
    projectId: 'jaiza-namaz',
    authDomain: 'jaiza-namaz.firebaseapp.com',
    storageBucket: 'jaiza-namaz.firebasestorage.app',
    measurementId: 'G-SV6SS2KG05',
  );

}